### ISSUE TITLE
Parallel read/write safe?

### ISSUE THREAD

**Issue by jdillard** [dgarcia360/sphinx-contributors#30]
Currently this extension is defaulted to run in serial mode only:
```
WARNING: the sphinx_contributors extension does not declare if it is safe for parallel reading, assuming it isn't - please ask the extension author to check and make it explicit
WARNING: doing serial read
```
From what I can tell by glancing over the code, it seems like it should be able to be marked [parallel read/write safe](https://www.sphinx-doc.org/en/master/extdev/index.html#extension-metadata)? I don't see it making any cross page calculations.

**Comment by dgarcia360** [comment]
I think so. I've submitted a PR that should address this issue https://github.com/dgarcia360/sphinx-contributors/pull/31
